# Generated by Django 2.2.6 on 2019-12-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_flor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flor',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='flor',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='flor',
            name='name',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
