# Generated by Django 2.2.6 on 2019-12-10 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0004_auto_20191210_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='flor',
            name='estado',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
