# Generated by Django 2.2.6 on 2019-12-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0005_flor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='flor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
