# Generated by Django 2.2.6 on 2019-12-10 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0006_flor_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flor',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='duracion',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='precio',
            new_name='valor',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='estado',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
